
development:
  adapter: mysql2 #postgresql
  host: localhost
  username: root #postgres
  password: root
  database: mertronic_devel
  pool: 5
  timeout: 5000

test:
  adapter: mysql2 #postgresql
  host: localhost
  username: root #postgres
  password: root
  database: mertronic_test
  pool: 5
  timeout: 5000


