
development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: root
  database: mertronic_devel
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username: postgres
  password: root
  database: mertronic_test
  pool: 5
  timeout: 5000


